### ISSUE TITLE
新規解答投稿フォーム後でエラー

### ISSUE THREAD

**Issue by falcon8823** [KosenVenture/RocketAnswer#100]
Markdown投稿のカラムがデフォルトだとnilだからだね．

![screencapture-localhost-3000-answers-1-1504630422720](https://user-images.githubusercontent.com/362095/30072738-3d3e33ac-92a6-11e7-9920-e3ab9f3f9cf7.png)

**Comment by falcon8823** [comment]
@Snow-Poijio このバグ修正やってください

**Comment by Snow-Poijio** [comment]
了解です
