### ISSUE TITLE
リポジトリURLの変更

### ISSUE THREAD

**Issue by zakuro9715** [KosenVenture/RocketAnswer#80]
リポジトリのURLが `https://github.com/KosenVenture/RocketAnswer` に変更されているので、フッタにあるリポジトリへのリンクのURLもそのように変更したほうがよい（リダイレクトされているので404などの問題はない）

**Comment by falcon8823** [comment]
この2箇所のURL修正です．

- https://github.com/KosenVenture/RocketAnswer/blob/develop/app/views/layouts/application.html.erb#L69
- https://github.com/KosenVenture/RocketAnswer/blob/develop/app/views/home/aboutus.html.erb#L17
