### ISSUE TITLE
編入体験談投稿機能

### ISSUE THREAD

**Issue by falcon8823** [KosenVenture/RocketAnswer#81]
基本的にHenTaiと同様な編入体験談投稿機能を実装する

http://kosen.herokuapp.com/stories

**Comment by Kousuke-N** [comment]
これはヘッダのタブに「編入体験談」的なものを入れて作るということでしょうか？

**Comment by falcon8823** [comment]
ですね。Slackに共有したExcelファイルをまず参照してみてください。

**Comment by Kousuke-N** [comment]
すみません確認していませんでした…

**Comment by Kousuke-N** [comment]
# 編入体験談テーブル(exp_story)
## リレーション
### belong
- 大学名(university)
- 学科(department)
### 要素
- 受験方法
- 合否
- 年度
- 自己紹介
- 動機
- 試験科目
- 試験
- 面接
- 使用した参考書
- アドバイス

# 投稿者情報テーブル(userに追記)
## リレーション
### belong
- 志望校
- 出身高校
## 要素
- 最高順位

# 出身高校テーブル
## 要素
- 学校名

# 志望校テーブル(wish_universityに追記)
## 要素
- 合否

**Comment by falcon8823** [comment]
出身高校は不適切かな．あっても高専だけど，普通の大学2年から編入という利用者も希にいるので．

志望校テーブルもほとんど使ってないので，ここもいらないかな．

**Comment by falcon8823** [comment]
出身の情報は，ユーザ登録時に入力しない可能性があるので，解答のテーブルにテキストのカラムを用意すればいいや．

（リレーションまでするかどうかは任せます．その場合，マスターデータとして高専一覧や足りなければユーザが追加できる仕組みを作った方がよさそうになるので，大変かも．）

**Comment by falcon8823** [comment]
あとは，試験科目のテーブルを分けるかどうか．
試験科目で絞り込みとか，検索機能をつけるということもできるようになります．

**Comment by falcon8823** [comment]
試験科目は，ユーザにはカンマ区切りでテキストで入力させて，裏で既に存在するものはそのIDと紐付けて，無いものは新しく生成するなんて方法もありかもね．

**Comment by Kousuke-N** [comment]
となると変更点は
- 出身高校テーブル→出身高専テーブル
- 志望校テーブルは廃止、要素としてuserに組み込み
- 試験科目のテーブル作成

ぐらいでしょうか？

**Comment by falcon8823** [comment]
まとめると，

- userに追記の情報も全て体験談テーブルに入れる
- high_schoolテーブルは不要
  - やるとしても，ちょっと名前を変えた方がよさげ．(Schoolモデルとかあった気がする…）
- wish_universityに追記も不要

**Comment by falcon8823** [comment]
一旦それでやってみようか．
やってみて，使い勝手を見て改めて指示を出すかも．

**Comment by Kousuke-N** [comment]
となると変更後はこんな感じでよろしいですか？
# 編入体験談テーブル(exp_story)
## リレーション
### belong
- 大学名(university)
- 学科(department)
### 要素
- 受験方法
- 合否
- 年度
- 自己紹介
- 動機
- 試験科目
- 試験
- 面接
- 使用した参考書
- アドバイス
- 志望校
- 合否
- 出身高専
- 最高順位

**Comment by falcon8823** [comment]
OKです．
出身学科も入れても良いかも．

出身高専ではなく出身校にしよう．

**Comment by Kousuke-N** [comment]
受験方法ってintegerかstringかどっちがいいですかね？

**Comment by falcon8823** [comment]
stringが良いと思います
こういう列挙型てきなのを使うときはenumerizeというgemもよく導入してます

**Comment by Kousuke-N** [comment]
このままだとものすごく入力欄が増えそうなのですが大丈夫ですか？

**Comment by Kousuke-N** [comment]
やはり学校情報userに追加してはいけませんか？
もし学校情報がnilなら入力してもらうという形ならおそらく問題にはならないと思うのですが・・・

**Comment by falcon8823** [comment]
> やはり学校情報userに追加してはいけませんか？

OKです．ただし，ユーザはこれが公開されることを同意していないと思うので，注意書きなどをお願いします．（フォームに表示される内容をならべておくといいかな）

**Comment by Kousuke-N** [comment]
了解です

**Comment by Kousuke-N** [comment]
学科の選択を学校を決めてから表示しようとanswerの_form.html.erbを参考にしているのですが、
'''
@exp_story.department.try(:school).try(:departments) || []
'''
の挙動がよくわかりません
なぜこれで表示されるのでしょうか？

**Comment by Kousuke-N** [comment]
すみません
自分の理解不足もあってドツボにはまってきたのでまだ未完成ですがチェックをお願いしてもいいですか？
今現時点の問題としては
- 学科が選択できない
- 実施年が数値として取り込まれない
- フォーム入力中のリロードやエラーが出た時入力したデータが残らない
- 解答投稿とコレクションセレクトの見た目が異なる

基本的に解答の投稿を参考にしています。
忙しいところ申し訳ありませんがよろしくおねがいします
