### ISSUE TITLE
MathJax & Markdownによる解答入力機能

### ISSUE THREAD

**Issue by falcon8823** [KosenVenture/RocketAnswer#82]
MathJaxとMarkdownによる解答入力機能をつくる

現状は，画像orPDFのアップロードになっているが，Markdown記法とTeX数式を直接入力することで，解答が整形されて表示される機能を実装する．

現状，コメント欄にはMarkdownが適用されている．手始めの作業としては，コメント欄をMathJaxに対応する．
そこから，それを参考に解答としてもMathJax+Markdownによって投稿できる機能を新規に実装する．

**Comment by falcon8823** [comment]
mathjax-railsというgemもあるが，これはメンテされてなさそうなので，使わないでおこう．

**Comment by falcon8823** [comment]
## 参考

- https://oku.edu.mie-u.ac.jp/~okumura/javascript/mathjax.html
- http://www.yamamo10.jp/~yamamoto/comp/WEB/MathJax/index.php

**Comment by Snow-Poijio** [comment]
answer_file にカラムを追加するか、新たにテーブルを作成するかどちらのほうがいいですか？
