### ISSUE TITLE
実施年や科目別でのソート

### ISSUE THREAD

**Issue by falcon8823** [KosenVenture/RocketAnswer#83]

**Comment by falcon8823** [comment]
このページに実施年と教科にリンクを付けて，そこをクリックすると，ソートできるようにしましょう．

- https://rocket-answer.com/universities/2/departments/216

**Comment by falcon8823** [comment]
Ransackというgemでできます．sort_linkというのを使います．

- https://github.com/activerecord-hackery/ransack
- https://github.com/activerecord-hackery/ransack#ransacks-sort_link-helper-creates-table-headers-that-are-sortable-links

**Comment by gntk** [comment]
sort_linkのusageを読んだのですが、`<%= sort_link(@q, :name) %>`の`@q, :name`にあたるものがどれなのかわかりません…
あと、書き換える(書き足す？)controllerはanswers_controller.rbであってますか…？
ヒントをよろしくお願いします……

**Comment by falcon8823** [comment]
> sort_linkのusageを読んだのですが、<%= sort_link(@q, :name) %>の@q, :nameにあたるものがどれなのかわかりません…

`:name` と言う部分は，モデルのカラム名です．
