### ISSUE TITLE
ユーザの投稿件数ランキング

### ISSUE THREAD

**Issue by falcon8823** [KosenVenture/RocketAnswer#84]
解答の投稿数を元に，ユーザランキングをつくる．

0件は表示しなくて良い．

tableによる一覧形式のページを作成する．

順位，ユーザ名，投稿数ぐらいを表示できるとよいです．

そこまで，投稿が沢山あるわけではないけども，直前1ヶ月や6ヶ月，総計のランキングと言う風に期間を分けてみるのも面白いとおもいます．

単純に，SQLで集計すればよいです．

**Comment by t-iwabuchi** [comment]
どちらの方法が良いのでしょうか。
- answersテーブルで、それぞれのuser_idについて、そのuser_idがいくつあるのかを集計&ソート 
- usersテーブルに要素として投稿数(answer)を追加

1番目は、アクセスがあるたびに集計しないといけないので、処理が重くなるかもしれません。
2番目は、今までの投稿を反映させなければいけないと思います。

また、ランキングへのリンクは、トップページのヘッダに追加すれば良いのでしょうか。

**Comment by falcon8823** [comment]
1番目を想定していました．

うまくSQLで集計してみてください．（Rubyでやってしまうと，重くなります）
